/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // docs: [
  //   category({
  //     label: '快速开始',
  //     path: 'quick-start',
  //     indexLink: {
  //       //description: null
  //     }
  //   }),
  //
  // ]


  /*
   category({
      label: '快速开始',
      items: ['quick-start/index']
    }),
   */


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;

// {
//   label, title = label,
// }

/*
{
      type: 'category',
      label: '快速开始',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/category/docusaurus-guides',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: ['quick-start/index'],
    }
 */



/**
 * 使用 `generated-index` 配合 `autogenerated` 生成。
 */
function indexCategory(config) {
  const indexLink = config.indexLink
  const configLink = config.link || {
    type: 'generated-index',
    title: indexLink.title || config.label, // 'Docusaurus Guides',
    description: indexLink.description, // Learn about the most important Docusaurus concepts!
    //slug: '/category/docusaurus-guides',
    keywords: indexLink.keywords || [], // ['guides'],
    image: indexLink.image || '/img/docusaurus.png',
  }

  return {
    type: 'category',
    label: config.label,
    link: configLink,
    items: [
      {
        type: 'autogenerated',
        dirName: config.path, // Generate sidebar slice from docs/tutorials/easy
      }
    ], // ['quick-start/index'],
  }
}